# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  # Global Application Variables
  vmImageName: 'macOS-10.14'

stages:
- stage: SetupDependencies
  displayName: Setup Dependencies
  jobs:
  - job: SetupDependenciesJob
    displayName: Setup Dependencies Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo "Testing java and npm version"
        echo $JAVA_HOME
        java -version
        node -v
        npm --version
        sudo npm install -g n
        sudo n stable
        node -v
        npm --version
        npm install -g appium
        appium -v
        appium >> 2&>1 /dev/null
        echo "*********************************"
        mvn --version
        echo "*********************************"
      displayName: 'Install Common  Depndencies'
    - task: Bash@3
      inputs:
        filePath: 'script/setup.sh'
      displayName: 'Install Emulator'
    - bash: |
        cd attendanceApp
        mvn install
        mvn clean compile test -X -DsuiteXmlFile=testingSingle -DdeviceName1=nexus -Dudid1="emulator-5554"
      displayName: 'Check'


