# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  # Global Application Variables
  vmImageName: 'macOS-10.14'

stages:
- stage: SetupDependencies
  displayName: Setup Dependencies
  jobs:
  - job: SetupDependenciesJob
    displayName: Setup Dependencies Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo "Testing java and npm version"
        java --version
        npm --version
      displayName: 'Install Common  Depndencies'
    - task: Bash@3
      inputs:
        filePath: 'script/setup.sh'
      displayName: 'Install Emulator'
    - bash: |
        npm --version
      displayName: 'Check'


