# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  # Global Application Variables
  vmImageName: 'macOS-10.14'

stages:
- stage: SetupDependencies
  displayName: Setup Dependencies
  jobs:
  - job: SetupDependenciesJob
    displayName: Setup Dependencies Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo "Installing java and npm "
        sudo npm install -g n
        sudo n stable
        npm install -g appium
      displayName: 'Install Common  Depndencies'
    - task: Bash@3
      inputs:
        filePath: 'script/setup.sh'
      displayName: 'Install Emulator'
    - bash: |
        adb devices
        cd attendanceApp
        mvn install -Dmaven.test.skip=true
        mvn clean compile test -DsuiteXmlFile=Single -DdeviceName1=nexus -Dudid1="emulator-5554"
      displayName: 'Check'



