# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- updating

parameters:
- name: EMAIL
  type: string
  default: hsaini@qasource.com
- name: EMAIL_PASS
  type: string
  default: password

variables:
  # Global Application Variables
  vmImageName: 'macOS-10.14'
  BUILD_NUM: '$(Build.BuildNumber)'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: SetupDependencies
  displayName: Setup Dependencies
  jobs:
  - job: SetupDependenciesJob
    displayName: Setup Dependencies Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo "Installing Common  Depndencies"
        sudo npm install -g n
        sudo n stable
        npm install -g appium allure-commandline
        pip install requests 
        pip install html2text
        pip install bs4
        pip install mime
        pip install argparse
      displayName: 'Install Common  Depndencies'
    - script: |
        python script/slack_notifications.py --html_report_path script/index.html
      displayName: 'Sending Slack Notification'
