# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  # Global Application Variables
  vmImageName: 'macOS-10.14'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: SetupDependencies
  displayName: Setup Dependencies
  jobs:
  - job: SetupDependenciesJob
    displayName: Setup Dependencies Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo "Installing Common  Depndencies"
        sudo npm install -g n
        sudo n stable
        npm install -g appium
      displayName: 'Install Common  Depndencies'
    - task: Bash@3
      inputs:
        filePath: 'script/setup.sh'
      displayName: 'Install Emulator'
    - bash: |
        adb devices
        cd attendanceApp
        mvn install -Dmaven.test.skip=true
        mvn clean compile test -DsuiteXmlFile=Parallel -DdeviceName1=google -Dudid1="emulator-5556" -DdeviceName2=nexus -Dudid2="emulator-5554"
      displayName: 'Testing Application'
    - publish: $(System.DefaultWorkingDirectory)/attendanceApp/target/allure-results
      artifact: report
    - bash: |
        echo "Send Slack Notification"
      




